services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   restart: unless-stopped
  #   depends_on:
  #     - mysql
  #   ports:
  #     - ${PGADMIN_PORT:-8081}:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-felipe@okino.dev}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS:-admin}
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin

volumes:
  mysql:
    driver: local
  # pgadmin:
  #   driver: local

      
  